### PR TITLE
Upgrade to 3.2.0

### PR DESCRIPTION
**Pull request by rgbkrk**
2.x-3.1 had a security vulnerability: http://seclists.org/oss-sec/2015/q2/779

@brint @JasonBoyles can you try this out with the current heat setup?

### CODE REVIEW

**Comment by brint** [comment]
testing

**Comment by rgbkrk** [comment]
I just realized that the nginx configuration will likely need updates (see https://github.com/jupyter/tmpnb-deploy/blob/91043d321c24beca803c4149cbc50dd7db7f0f64/roles/proxy/templates/nginx.conf.j2#L61)

**Comment by brint** [comment]
It does deploy with 3.2.0, not sure what out of there needs to be changed. I will defer to you on that one.

**Comment by rgbkrk** [comment]
I'd make sure you can run code inside a notebook primarily.

**Comment by brint** [comment]
I could launch a terminal and a notebook. I was able to do some simple python things in the notebook as well.

**Comment by rgbkrk** [comment]
Ok, awesome.

**Pull request merged**
